// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package tyrex.server;

public final class TransactionServer_Stub
    extends java.rmi.server.RemoteStub
    implements tyrex.server.RemoteTransactionServer, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_createRemoteTransaction_0;
    
    static {
	try {
	    $method_createRemoteTransaction_0 = tyrex.server.RemoteTransactionServer.class.getMethod("createRemoteTransaction", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public TransactionServer_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of createRemoteTransaction()
    public byte[] createRemoteTransaction()
	throws java.rmi.RemoteException, javax.transaction.SystemException
    {
	try {
	    Object $result = ref.invoke(this, $method_createRemoteTransaction_0, null, 5770545206526485635L);
	    return ((byte[]) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (javax.transaction.SystemException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
